/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackofficeRouteImport } from './routes/_backoffice'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BackofficeClientesRouteImport } from './routes/_backoffice/clientes'
import { Route as BackofficeConfiguracoesRouteImport } from './routes/_backoffice/configuracoes'
import { Route as BackofficeDashboardRouteImport } from './routes/_backoffice/dashboard'
import { Route as BackofficeFornecedoresRouteImport } from './routes/_backoffice/fornecedores'
import { Route as BackofficeIntegracoesRouteImport } from './routes/_backoffice/integracoes'
import { Route as BackofficeRelatoriosRouteImport } from './routes/_backoffice/relatorios'
import { Route as BackofficeVendedoresRouteImport } from './routes/_backoffice/vendedores'
import { Route as BackofficeCaixaIndexRouteImport } from './routes/_backoffice/caixa.index'
import { Route as BackofficeCaixaIdRouteImport } from './routes/_backoffice/caixa.$id'
import { Route as BackofficeCampanhasIndexRouteImport } from './routes/_backoffice/campanhas/index'
import { Route as BackofficeCampanhasIdRouteImport } from './routes/_backoffice/campanhas/$id'
import { Route as BackofficeColecoesIndexRouteImport } from './routes/_backoffice/colecoes/index'
import { Route as BackofficeColecoesIdRouteImport } from './routes/_backoffice/colecoes/$id'
import { Route as BackofficeEstoqueIndexRouteImport } from './routes/_backoffice/estoque/index'
import { Route as BackofficeEstoqueProdutoIdRouteImport } from './routes/_backoffice/estoque/$produtoId'
import { Route as BackofficeProdutosIndexRouteImport } from './routes/_backoffice/produtos/index'
import { Route as BackofficeProdutosNovoRouteImport } from './routes/_backoffice/produtos/novo'
import { Route as BackofficeVendasIndexRouteImport } from './routes/_backoffice/vendas.index'
import { Route as BackofficeVendasIdRouteImport } from './routes/_backoffice/vendas.$id'
import { Route as BackofficeProdutosIdIndexRouteImport } from './routes/_backoffice/produtos/$id/index'
import { Route as BackofficeProdutosIdEditarRouteImport } from './routes/_backoffice/produtos/$id/editar'
import { Route as BackofficeProdutosIdVariantesRouteImport } from './routes/_backoffice/produtos/$id/variantes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/_backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeClientesRoute = BackofficeClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeConfiguracoesRoute = BackofficeConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeDashboardRoute = BackofficeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeFornecedoresRoute = BackofficeFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeIntegracoesRoute = BackofficeIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeRelatoriosRoute = BackofficeRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeVendedoresRoute = BackofficeVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeCaixaIndexRoute = BackofficeCaixaIndexRouteImport.update({
  id: '/caixa/',
  path: '/caixa/',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeCaixaIdRoute = BackofficeCaixaIdRouteImport.update({
  id: '/caixa/$id',
  path: '/caixa/$id',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeCampanhasIndexRoute =
  BackofficeCampanhasIndexRouteImport.update({
    id: '/campanhas/',
    path: '/campanhas/',
    getParentRoute: () => BackofficeRoute,
  } as any)
const BackofficeCampanhasIdRoute = BackofficeCampanhasIdRouteImport.update({
  id: '/campanhas/$id',
  path: '/campanhas/$id',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeColecoesIndexRoute = BackofficeColecoesIndexRouteImport.update({
  id: '/colecoes/',
  path: '/colecoes/',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeColecoesIdRoute = BackofficeColecoesIdRouteImport.update({
  id: '/colecoes/$id',
  path: '/colecoes/$id',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeEstoqueIndexRoute = BackofficeEstoqueIndexRouteImport.update({
  id: '/estoque/',
  path: '/estoque/',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeEstoqueProdutoIdRoute =
  BackofficeEstoqueProdutoIdRouteImport.update({
    id: '/estoque/$produtoId',
    path: '/estoque/$produtoId',
    getParentRoute: () => BackofficeRoute,
  } as any)
const BackofficeProdutosIndexRoute = BackofficeProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeProdutosNovoRoute = BackofficeProdutosNovoRouteImport.update({
  id: '/produtos/novo',
  path: '/produtos/novo',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeVendasIndexRoute = BackofficeVendasIndexRouteImport.update({
  id: '/vendas/',
  path: '/vendas/',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeVendasIdRoute = BackofficeVendasIdRouteImport.update({
  id: '/vendas/$id',
  path: '/vendas/$id',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeProdutosIdIndexRoute =
  BackofficeProdutosIdIndexRouteImport.update({
    id: '/produtos/$id/',
    path: '/produtos/$id/',
    getParentRoute: () => BackofficeRoute,
  } as any)
const BackofficeProdutosIdEditarRoute =
  BackofficeProdutosIdEditarRouteImport.update({
    id: '/produtos/$id/editar',
    path: '/produtos/$id/editar',
    getParentRoute: () => BackofficeRoute,
  } as any)
const BackofficeProdutosIdVariantesRoute =
  BackofficeProdutosIdVariantesRouteImport.update({
    id: '/produtos/$id/variantes',
    path: '/produtos/$id/variantes',
    getParentRoute: () => BackofficeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/clientes': typeof BackofficeClientesRoute
  '/configuracoes': typeof BackofficeConfiguracoesRoute
  '/dashboard': typeof BackofficeDashboardRoute
  '/fornecedores': typeof BackofficeFornecedoresRoute
  '/integracoes': typeof BackofficeIntegracoesRoute
  '/relatorios': typeof BackofficeRelatoriosRoute
  '/vendedores': typeof BackofficeVendedoresRoute
  '/caixa/$id': typeof BackofficeCaixaIdRoute
  '/campanhas/$id': typeof BackofficeCampanhasIdRoute
  '/colecoes/$id': typeof BackofficeColecoesIdRoute
  '/estoque/$produtoId': typeof BackofficeEstoqueProdutoIdRoute
  '/produtos/novo': typeof BackofficeProdutosNovoRoute
  '/vendas/$id': typeof BackofficeVendasIdRoute
  '/caixa/': typeof BackofficeCaixaIndexRoute
  '/campanhas/': typeof BackofficeCampanhasIndexRoute
  '/colecoes/': typeof BackofficeColecoesIndexRoute
  '/estoque/': typeof BackofficeEstoqueIndexRoute
  '/produtos/': typeof BackofficeProdutosIndexRoute
  '/vendas/': typeof BackofficeVendasIndexRoute
  '/produtos/$id/editar': typeof BackofficeProdutosIdEditarRoute
  '/produtos/$id/variantes': typeof BackofficeProdutosIdVariantesRoute
  '/produtos/$id/': typeof BackofficeProdutosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/clientes': typeof BackofficeClientesRoute
  '/configuracoes': typeof BackofficeConfiguracoesRoute
  '/dashboard': typeof BackofficeDashboardRoute
  '/fornecedores': typeof BackofficeFornecedoresRoute
  '/integracoes': typeof BackofficeIntegracoesRoute
  '/relatorios': typeof BackofficeRelatoriosRoute
  '/vendedores': typeof BackofficeVendedoresRoute
  '/caixa/$id': typeof BackofficeCaixaIdRoute
  '/campanhas/$id': typeof BackofficeCampanhasIdRoute
  '/colecoes/$id': typeof BackofficeColecoesIdRoute
  '/estoque/$produtoId': typeof BackofficeEstoqueProdutoIdRoute
  '/produtos/novo': typeof BackofficeProdutosNovoRoute
  '/vendas/$id': typeof BackofficeVendasIdRoute
  '/caixa': typeof BackofficeCaixaIndexRoute
  '/campanhas': typeof BackofficeCampanhasIndexRoute
  '/colecoes': typeof BackofficeColecoesIndexRoute
  '/estoque': typeof BackofficeEstoqueIndexRoute
  '/produtos': typeof BackofficeProdutosIndexRoute
  '/vendas': typeof BackofficeVendasIndexRoute
  '/produtos/$id/editar': typeof BackofficeProdutosIdEditarRoute
  '/produtos/$id/variantes': typeof BackofficeProdutosIdVariantesRoute
  '/produtos/$id': typeof BackofficeProdutosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_backoffice': typeof BackofficeRouteWithChildren
  '/login': typeof LoginRoute
  '/_backoffice/clientes': typeof BackofficeClientesRoute
  '/_backoffice/configuracoes': typeof BackofficeConfiguracoesRoute
  '/_backoffice/dashboard': typeof BackofficeDashboardRoute
  '/_backoffice/fornecedores': typeof BackofficeFornecedoresRoute
  '/_backoffice/integracoes': typeof BackofficeIntegracoesRoute
  '/_backoffice/relatorios': typeof BackofficeRelatoriosRoute
  '/_backoffice/vendedores': typeof BackofficeVendedoresRoute
  '/_backoffice/caixa/$id': typeof BackofficeCaixaIdRoute
  '/_backoffice/campanhas/$id': typeof BackofficeCampanhasIdRoute
  '/_backoffice/colecoes/$id': typeof BackofficeColecoesIdRoute
  '/_backoffice/estoque/$produtoId': typeof BackofficeEstoqueProdutoIdRoute
  '/_backoffice/produtos/novo': typeof BackofficeProdutosNovoRoute
  '/_backoffice/vendas/$id': typeof BackofficeVendasIdRoute
  '/_backoffice/caixa/': typeof BackofficeCaixaIndexRoute
  '/_backoffice/campanhas/': typeof BackofficeCampanhasIndexRoute
  '/_backoffice/colecoes/': typeof BackofficeColecoesIndexRoute
  '/_backoffice/estoque/': typeof BackofficeEstoqueIndexRoute
  '/_backoffice/produtos/': typeof BackofficeProdutosIndexRoute
  '/_backoffice/vendas/': typeof BackofficeVendasIndexRoute
  '/_backoffice/produtos/$id/editar': typeof BackofficeProdutosIdEditarRoute
  '/_backoffice/produtos/$id/variantes': typeof BackofficeProdutosIdVariantesRoute
  '/_backoffice/produtos/$id/': typeof BackofficeProdutosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/fornecedores'
    | '/integracoes'
    | '/relatorios'
    | '/vendedores'
    | '/caixa/$id'
    | '/campanhas/$id'
    | '/colecoes/$id'
    | '/estoque/$produtoId'
    | '/produtos/novo'
    | '/vendas/$id'
    | '/caixa/'
    | '/campanhas/'
    | '/colecoes/'
    | '/estoque/'
    | '/produtos/'
    | '/vendas/'
    | '/produtos/$id/editar'
    | '/produtos/$id/variantes'
    | '/produtos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/fornecedores'
    | '/integracoes'
    | '/relatorios'
    | '/vendedores'
    | '/caixa/$id'
    | '/campanhas/$id'
    | '/colecoes/$id'
    | '/estoque/$produtoId'
    | '/produtos/novo'
    | '/vendas/$id'
    | '/caixa'
    | '/campanhas'
    | '/colecoes'
    | '/estoque'
    | '/produtos'
    | '/vendas'
    | '/produtos/$id/editar'
    | '/produtos/$id/variantes'
    | '/produtos/$id'
  id:
    | '__root__'
    | '/'
    | '/_backoffice'
    | '/login'
    | '/_backoffice/clientes'
    | '/_backoffice/configuracoes'
    | '/_backoffice/dashboard'
    | '/_backoffice/fornecedores'
    | '/_backoffice/integracoes'
    | '/_backoffice/relatorios'
    | '/_backoffice/vendedores'
    | '/_backoffice/caixa/$id'
    | '/_backoffice/campanhas/$id'
    | '/_backoffice/colecoes/$id'
    | '/_backoffice/estoque/$produtoId'
    | '/_backoffice/produtos/novo'
    | '/_backoffice/vendas/$id'
    | '/_backoffice/caixa/'
    | '/_backoffice/campanhas/'
    | '/_backoffice/colecoes/'
    | '/_backoffice/estoque/'
    | '/_backoffice/produtos/'
    | '/_backoffice/vendas/'
    | '/_backoffice/produtos/$id/editar'
    | '/_backoffice/produtos/$id/variantes'
    | '/_backoffice/produtos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackofficeRoute: typeof BackofficeRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_backoffice': {
      id: '/_backoffice'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_backoffice/clientes': {
      id: '/_backoffice/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof BackofficeClientesRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/configuracoes': {
      id: '/_backoffice/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof BackofficeConfiguracoesRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/dashboard': {
      id: '/_backoffice/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof BackofficeDashboardRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/fornecedores': {
      id: '/_backoffice/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof BackofficeFornecedoresRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/integracoes': {
      id: '/_backoffice/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof BackofficeIntegracoesRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/relatorios': {
      id: '/_backoffice/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof BackofficeRelatoriosRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/vendedores': {
      id: '/_backoffice/vendedores'
      path: '/vendedores'
      fullPath: '/vendedores'
      preLoaderRoute: typeof BackofficeVendedoresRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/caixa/': {
      id: '/_backoffice/caixa/'
      path: '/caixa'
      fullPath: '/caixa/'
      preLoaderRoute: typeof BackofficeCaixaIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/caixa/$id': {
      id: '/_backoffice/caixa/$id'
      path: '/caixa/$id'
      fullPath: '/caixa/$id'
      preLoaderRoute: typeof BackofficeCaixaIdRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/campanhas/': {
      id: '/_backoffice/campanhas/'
      path: '/campanhas'
      fullPath: '/campanhas/'
      preLoaderRoute: typeof BackofficeCampanhasIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/campanhas/$id': {
      id: '/_backoffice/campanhas/$id'
      path: '/campanhas/$id'
      fullPath: '/campanhas/$id'
      preLoaderRoute: typeof BackofficeCampanhasIdRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/colecoes/': {
      id: '/_backoffice/colecoes/'
      path: '/colecoes'
      fullPath: '/colecoes/'
      preLoaderRoute: typeof BackofficeColecoesIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/colecoes/$id': {
      id: '/_backoffice/colecoes/$id'
      path: '/colecoes/$id'
      fullPath: '/colecoes/$id'
      preLoaderRoute: typeof BackofficeColecoesIdRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/estoque/': {
      id: '/_backoffice/estoque/'
      path: '/estoque'
      fullPath: '/estoque/'
      preLoaderRoute: typeof BackofficeEstoqueIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/estoque/$produtoId': {
      id: '/_backoffice/estoque/$produtoId'
      path: '/estoque/$produtoId'
      fullPath: '/estoque/$produtoId'
      preLoaderRoute: typeof BackofficeEstoqueProdutoIdRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/produtos/': {
      id: '/_backoffice/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof BackofficeProdutosIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/produtos/novo': {
      id: '/_backoffice/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/produtos/novo'
      preLoaderRoute: typeof BackofficeProdutosNovoRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/vendas/': {
      id: '/_backoffice/vendas/'
      path: '/vendas'
      fullPath: '/vendas/'
      preLoaderRoute: typeof BackofficeVendasIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/vendas/$id': {
      id: '/_backoffice/vendas/$id'
      path: '/vendas/$id'
      fullPath: '/vendas/$id'
      preLoaderRoute: typeof BackofficeVendasIdRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/produtos/$id/': {
      id: '/_backoffice/produtos/$id/'
      path: '/produtos/$id'
      fullPath: '/produtos/$id/'
      preLoaderRoute: typeof BackofficeProdutosIdIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/produtos/$id/editar': {
      id: '/_backoffice/produtos/$id/editar'
      path: '/produtos/$id/editar'
      fullPath: '/produtos/$id/editar'
      preLoaderRoute: typeof BackofficeProdutosIdEditarRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/_backoffice/produtos/$id/variantes': {
      id: '/_backoffice/produtos/$id/variantes'
      path: '/produtos/$id/variantes'
      fullPath: '/produtos/$id/variantes'
      preLoaderRoute: typeof BackofficeProdutosIdVariantesRouteImport
      parentRoute: typeof BackofficeRoute
    }
  }
}

interface BackofficeRouteChildren {
  BackofficeClientesRoute: typeof BackofficeClientesRoute
  BackofficeConfiguracoesRoute: typeof BackofficeConfiguracoesRoute
  BackofficeDashboardRoute: typeof BackofficeDashboardRoute
  BackofficeFornecedoresRoute: typeof BackofficeFornecedoresRoute
  BackofficeIntegracoesRoute: typeof BackofficeIntegracoesRoute
  BackofficeRelatoriosRoute: typeof BackofficeRelatoriosRoute
  BackofficeVendedoresRoute: typeof BackofficeVendedoresRoute
  BackofficeCaixaIdRoute: typeof BackofficeCaixaIdRoute
  BackofficeCampanhasIdRoute: typeof BackofficeCampanhasIdRoute
  BackofficeColecoesIdRoute: typeof BackofficeColecoesIdRoute
  BackofficeEstoqueProdutoIdRoute: typeof BackofficeEstoqueProdutoIdRoute
  BackofficeProdutosNovoRoute: typeof BackofficeProdutosNovoRoute
  BackofficeVendasIdRoute: typeof BackofficeVendasIdRoute
  BackofficeCaixaIndexRoute: typeof BackofficeCaixaIndexRoute
  BackofficeCampanhasIndexRoute: typeof BackofficeCampanhasIndexRoute
  BackofficeColecoesIndexRoute: typeof BackofficeColecoesIndexRoute
  BackofficeEstoqueIndexRoute: typeof BackofficeEstoqueIndexRoute
  BackofficeProdutosIndexRoute: typeof BackofficeProdutosIndexRoute
  BackofficeVendasIndexRoute: typeof BackofficeVendasIndexRoute
  BackofficeProdutosIdEditarRoute: typeof BackofficeProdutosIdEditarRoute
  BackofficeProdutosIdVariantesRoute: typeof BackofficeProdutosIdVariantesRoute
  BackofficeProdutosIdIndexRoute: typeof BackofficeProdutosIdIndexRoute
}

const BackofficeRouteChildren: BackofficeRouteChildren = {
  BackofficeClientesRoute: BackofficeClientesRoute,
  BackofficeConfiguracoesRoute: BackofficeConfiguracoesRoute,
  BackofficeDashboardRoute: BackofficeDashboardRoute,
  BackofficeFornecedoresRoute: BackofficeFornecedoresRoute,
  BackofficeIntegracoesRoute: BackofficeIntegracoesRoute,
  BackofficeRelatoriosRoute: BackofficeRelatoriosRoute,
  BackofficeVendedoresRoute: BackofficeVendedoresRoute,
  BackofficeCaixaIdRoute: BackofficeCaixaIdRoute,
  BackofficeCampanhasIdRoute: BackofficeCampanhasIdRoute,
  BackofficeColecoesIdRoute: BackofficeColecoesIdRoute,
  BackofficeEstoqueProdutoIdRoute: BackofficeEstoqueProdutoIdRoute,
  BackofficeProdutosNovoRoute: BackofficeProdutosNovoRoute,
  BackofficeVendasIdRoute: BackofficeVendasIdRoute,
  BackofficeCaixaIndexRoute: BackofficeCaixaIndexRoute,
  BackofficeCampanhasIndexRoute: BackofficeCampanhasIndexRoute,
  BackofficeColecoesIndexRoute: BackofficeColecoesIndexRoute,
  BackofficeEstoqueIndexRoute: BackofficeEstoqueIndexRoute,
  BackofficeProdutosIndexRoute: BackofficeProdutosIndexRoute,
  BackofficeVendasIndexRoute: BackofficeVendasIndexRoute,
  BackofficeProdutosIdEditarRoute: BackofficeProdutosIdEditarRoute,
  BackofficeProdutosIdVariantesRoute: BackofficeProdutosIdVariantesRoute,
  BackofficeProdutosIdIndexRoute: BackofficeProdutosIdIndexRoute,
}

const BackofficeRouteWithChildren = BackofficeRoute._addFileChildren(
  BackofficeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackofficeRoute: BackofficeRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
